---
# since certspull populates files/certs/<fqdn>, the following is required for the target:
#   - create cert directory
#   - copy privkey.pem and fullchain.pem to it
# a separate role can then put the ssl-enabled template on the target, check syntax, and restart nginx
- name: create ssl certs folder if not found
  ansible.builtin.file:
    path: "{{ certs_target_folder }}"
    state: directory
    mode: '0750'
  tags:
    - certupdate

- name: copy certs to target
  ansible.builtin.copy:
    src: "{{ certs_local_prefix }}/{{ server_fqdn }}/{{ item.filename }}"
    dest: "{{ certs_target_folder }}/{{ item.filename }}"
    mode: "{{ item.mode }}"
  loop: "{{ cert_info }}"
  tags:
    - certupdate

# while a handler exists, it's not called out here since this could be part of a larger playbook
